/* Generated By:JavaCC: Do not edit this line. RelangTreeConstants.java Version 5.0 */
package org.reldb.relang.parser.ast;

public interface RelangTreeConstants
{
  public int JJTCODE = 0;
  public int JJTSTATEMENT = 1;
  public int JJTBLOCK = 2;
  public int JJTPARMLIST = 3;
  public int JJTFNBODY = 4;
  public int JJTFNDEF = 5;
  public int JJTRETURNEXPRESSION = 6;
  public int JJTVOID = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTIFSTATEMENT = 9;
  public int JJTFORLOOP = 10;
  public int JJTWRITE = 11;
  public int JJTCALL = 12;
  public int JJTARGLIST = 13;
  public int JJTOR = 14;
  public int JJTAND = 15;
  public int JJTCOMPEQUAL = 16;
  public int JJTCOMPNEQUAL = 17;
  public int JJTCOMPGTE = 18;
  public int JJTCOMPLTE = 19;
  public int JJTCOMPGT = 20;
  public int JJTCOMPLT = 21;
  public int JJTADD = 22;
  public int JJTSUBTRACT = 23;
  public int JJTTIMES = 24;
  public int JJTDIVIDE = 25;
  public int JJTUNARYNOT = 26;
  public int JJTUNARYPLUS = 27;
  public int JJTUNARYMINUS = 28;
  public int JJTFNINVOKE = 29;
  public int JJTIDENTIFIER = 30;
  public int JJTDEREFERENCE = 31;
  public int JJTINTEGER = 32;
  public int JJTRATIONAL = 33;
  public int JJTTRUE = 34;
  public int JJTFALSE = 35;


  public String[] jjtNodeName = {
    "Code",
    "Statement",
    "Block",
    "Parmlist",
    "FnBody",
    "FnDef",
    "ReturnExpression",
    "void",
    "Assignment",
    "IfStatement",
    "ForLoop",
    "Write",
    "Call",
    "ArgList",
    "Or",
    "And",
    "CompEqual",
    "CompNequal",
    "CompGTE",
    "CompLTE",
    "CompGT",
    "CompLT",
    "Add",
    "Subtract",
    "Times",
    "Divide",
    "UnaryNot",
    "UnaryPlus",
    "UnaryMinus",
    "FnInvoke",
    "Identifier",
    "Dereference",
    "Integer",
    "Rational",
    "True",
    "False",
  };
}
/* JavaCC - OriginalChecksum=c76d2bbaeaad78f39edf05c689f7cc10 (do not edit this line) */
